name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
 build:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |-
        docker build . --file Dockerfile --tag simplepyt:$(date +%s)
    - id: auth
      name: 'Authentication with'
      uses: 'google-github-actions/auth@v2'
      with:
      
        project_id: 'learned-raceway-418714'
        workload_identity_provider: 'projects/904969968668/locations/global/workloadIdentityPools/github-oidc-pool-v2/providers/github-oidc-provider'
        service_account: widp-314@learned-raceway-418714.iam.gserviceaccount.com
      
    - id : readFile
      name: "Read JSON"
      run: |-
          cat ${{ steps.auth.outputs.credentials_file_path }}"
    - id : 'testAuz' 
      name: "test"
      uses: docker/login-action@v3
      with:
        registry: asia-south1-docker.pkg.dev
        username: _json_key
        password: "${{ steps.auth.outputs.credentials_file_path }}"
