name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
 build:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |-
        docker build . --file Dockerfile --tag simplepyt:$(date +%s)
    - id: auth
      name: 'Authentication with'
      uses: 'google-github-actions/auth@v2'
      with:
        
        project_id: 'learned-raceway-418714'
        workload_identity_provider: 'projects/904969968668/locations/global/workloadIdentityPools/github-oidc-pool-v2/providers/github-oidc-provider'
        service_account: 'widp-314@learned-raceway-418714.iam.gserviceaccount.com'
      
    - id : readFile
      name: "Read JSON"
      run: |-
          cat "${{ steps.auth.outputs.credentials_file_path }}"

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        version: '>= 363.0.0'
    - name : Running gcloud command
      run : 'gcloud info'
    - id: 'docker_login'
      name : "Docker Login"
      run: |- 
           gcloud components update
           gcloud auth configure-docker https://asia-south1-docker.pkg.dev/
           gcloud artifacts locations list
           cat "${{ steps.auth.outputs.credentials_file_path }}" | docker login -u _json_key_base64 --password-stdin https://asia-south1-docker.pkg.dev/v2
 
