name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
 build:
    permissions:
      contents: 'read'
      id-token: 'write'
 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |-
        docker build . --file Dockerfile --tag simplepyt:$(date +%s)
    - uses: 'google-github-actions/auth@v2'
      name: 'auth'
      with:
        create_credentials_file: 'true'
        project_id: 'learned-raceway-418714'
        workload_identity_provider: 'projects/904969968668/locations/global/workloadIdentityPools/github-oidc-pool/providers/github-oidc-provider'
    - id: 'gcloud'
      name: 'gcloud command'
      run: |-
        gcloud init --no-browser
        gcloud auth activate-service-account widp-demo@learned-raceway-418714.iam.gserviceaccount.com --key-file="${{ steps.auth.outputs.credentials_file_path }}" --project="learned-raceway-418714"
        echo "Praise the Lord"
        gcloud auth login --no-launch-browser --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
        gcloud services list
